# Generated by Django 5.2.8 on 2025-11-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightsplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('HR', 'Human Rights'), ('GV', 'Gender Violence'), ('DV', 'Domestic Violence'), ('WL', 'Whistleblowing'), ('OT', 'Other')], default='OT', max_length=20),
        ),
    ]
