# Generated by Django 5.2.8 on 2025-11-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightsplace', '0002_report_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional contact email for communication and verification purposes.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Mark as verified after admin approval (applies to NGOs and Lawyers).'),
        ),
    ]
