# Generated by Django 5.2.8 on 2025-11-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightsplace', '0003_userprofile_email_userprofile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='organization',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Organization name (required for NGOs).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wants_contact',
            field=models.BooleanField(default=False, help_text='If true, user is willing to be contacted about their report.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional contact email for communication and verification.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional phone contact.', max_length=20, null=True),
        ),
    ]
