# Generated by Django 5.2.8 on 2025-11-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightsplace', '0004_remove_userprofile_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text='City of residence or operation.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enrolment_number',
            field=models.CharField(blank=True, help_text="Lawyer's official enrolment number (NBA verified).", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rc_number',
            field=models.CharField(blank=True, help_text='Required for NGOs.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='Optional field: area of legal specialty.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, help_text='State of residence or operation.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email (required for NGOs and Lawyers).', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True after admin verification for Lawyers/NGOs.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='General location or address.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Required for NGOs.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number (required for NGOs and Lawyers).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wants_contact',
            field=models.BooleanField(default=False, help_text='Whether the reporter wishes to be contacted.'),
        ),
    ]
